# Generated by Django 4.2.5 on 2023-09-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_todo_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_created',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
